### ISSUE TITLE
Thursday Peer to Peer code review

### ISSUE THREAD

**Issue by nwakauc** [Kashif-Saleem-Ghuman/JavaScript-Capstone-Project#27]
##  Highlight 🐱‍🏍

- You used JavaScript best practices 👏
- All linters are passing ✔
- Good use of gitflow 👌
- It will be good if you implement the likes functionality

**Comment by ohyajk** [comment]
###🙏🙏🙏🙏🙏
Thank you for your review. We have added this functionality.

![MimosaMimGIF](https://user-images.githubusercontent.com/114587346/210972710-8f2f38ca-bdb2-41be-a4f4-f363d1f2fa6d.gif)
